### ISSUE TITLE
[Issue] Uncaught exception : CALayerInvalidGeometry 

### ISSUE THREAD

**Issue by jewilhel** [alexdrone/Render#78] opened 2017-08-16 15:28 UTC
I pulled the latest commit and I'm getting this error:

` *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'
*** First throw call stack:`

been trying to track down the reason. Nothings changed in my code.

**Comment by jewilhel** [comment] 2017-08-16 15:51
If I roll back before commit: `Fix scrolling issue with ComponentController and UIScrollView` then the errors go away. Not sure if I need to update my code in some way to resolve the issue.

**Comment by alexdrone** [comment] 2017-08-19 14:17
are you on xcode9?

**Comment by zdnk** [comment] 2017-08-19 18:28
Happens to me sometimes too. I always have to figure some workaround. It usually happens when you add component too soon and trying to render it.
Also on iPad, there are some difficulties with `ComponentController` - somewhat wrongfully centered/placed root component view.

**Comment by alexdrone** [comment] 2017-08-19 18:40
where do you call addComponentToViewControllerHierarchy ?

**Comment by zdnk** [comment] 2017-08-19 18:40
`loadView()` method, but I believe I tried `viewDidLoad()` too

**Comment by alexdrone** [comment] 2017-08-19 18:42
`viewDidLoad ` is the preferred entry point. Will try on iPad to see if I can repro

**Comment by zdnk** [comment] 2017-08-19 18:45
When I get to work tomorrow I will do some testing and provide correct information regarding this. But with `UIScrollView` I am 100% there was a different behaviour iPhone vs iPad with `ComponentController` and `renderComponent()` and I could not use it in the end.

**Comment by jewilhel** [comment] 2017-08-20 19:01
I'm using Xcode 8.3.3, nothings changed on my end expect I pulled the latest changes. I'm also adding `addComponentToViewControllerHierarchy()` in  `viewDidLoad()`.
I just tried updating to `preventComponentUpdate block` but I still get the same error.

**Comment by alexdrone** [comment] 2017-08-21 09:31
This should be now fixed on HEAD (no need to use preventComponentUpdate)

**Closed as completed by alexdrone** 2017-08-21 09:31 UTC

**Comment by jewilhel** [comment] 2017-08-21 20:46
Hey, Thank you Alex! That really fixed the issue that I was having with Xcode 8.3.3. 

I was curious if the Render framework works with Xcode 9 already? Does it support Swift 3.2? I have been hesitant to move forward until my project dependancies do as well.

Again, thank you! :)

**Comment by zdnk** [comment] 2017-08-21 20:52
I can confirm it works in Xcode 9 beta5 and Swift 3.2. I am using it since beta 5 was released.

**Comment by jewilhel** [comment] 2017-08-21 20:54
That's good to know, thank you for your feedback! :)
